### ISSUE TITLE
Please upload the pre-train weight

### ISSUE THREAD

**Issue by stevenwuaggie507** [pvtien96/D2DP#4]
@pvtien96 , Please upload the pre-train weight, EgteaGaze_mask_rcnn_R_50_FPN_3x/model_final.pth", then I can test the performance, thank you.

**Comment by vantienpham** [comment]
@stevenwuaggie507 you can download with the link provided in readme

**Comment by stevenwuaggie507** [comment]
@pvtien96, successfully download the pre-train weight file, model_final.pth, Thank you for quickly response.
