### ISSUE TITLE
Train on custom data set

### ISSUE THREAD

**Issue by geosaRW** [pvtien96/D2DP#5]
Hey pvtien,

I am desperately looking for a guide of how to train the deep sort on a custom dataset.
I saw your github and you have done some very nice work. As I understand the default deep sort is trained on humans but you did trained it with hands. 
Could you please give me a guideline of how to procceed with it.
I am also using detectron2 for my detections.

Thanks a lot.

**Comment by vantienpham** [comment]
@geosaRW Yes, you're right. 
At first I read many sources related to customize deepsort.
I base my deep appearance descriptor mainly on [this repo](https://github.com/ZQPei/deep_sort_pytorch).
But it still requires some tricks, you need a re-identification dataset, put each id in a folder (I read these on a chinese web but I currently forget the link)
Or you may want to refer [deepsort for vehicle](https://blog.csdn.net/weixin_38757163/article/details/111150364), many paper for this problem are published.
Glad to help!
